version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: JobPortal-container
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:123456@mongodb:27017/test?authSource=admin

volumes:
  mongo-data:
